CREATE TABLE MasterKategori(
	KategoriCode VARCHAR(255) NOT NULL
		PRIMARY KEY,
     Name VARCHAR(255) NOT NULL,
     CreatedAt DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
     CreatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
     UpdatedAt DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
     UpdatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM'
);

CREATE TABLE MasterBarang
(
	SKUID VARCHAR(255) NOT NULL
		PRIMARY KEY,
    KategoriCode VARCHAR(255) NOT NULL,
	Name VARCHAR(255) NOT NULL,
     CreatedAt DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
     CreatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
     UpdatedAt DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
     UpdatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
		FOREIGN KEY (KategoriCode) REFERENCES MasterKategori(KategoriCode)
);

CREATE TABLE Outlet
(
	OutletCode VARCHAR(255) NOT NULL
		PRIMARY KEY,
     Name VARCHAR(255) NOT NULL,
     CreatedAt DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
     CreatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
     UpdatedAt DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
     UpdatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM'
);

CREATE TABLE MasterGudang
(
	GudangCode VARCHAR(255) NOT NULL
		PRIMARY KEY,
     OutletCode VARCHAR(255) NOT NULL,
    Name VARCHAR(255) NOT NULL,
	CreatedAt DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
     CreatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
     UpdatedAt DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
     UpdatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
		FOREIGN KEY (OutletCode) REFERENCES Outlet(OutletCode)
);

CREATE TABLE UserRoleEnum
(
	UserRoleEnumId INT PRIMARY KEY auto_increment,
	Name VARCHAR(255) NOT NULL
);

CREATE TABLE MasterUser
(
	UserCode VARCHAR(255) NOT NULL
	  PRIMARY KEY,
	UserRoleEnumId INT NOT NULL ,
        FOREIGN KEY (UserRoleEnumId) REFERENCES UserRoleEnum (UserRoleEnumId), 
     Name VARCHAR(255) NOT NULL,
     Password VARCHAR(255) NOT NULL,
     Email VARCHAR(255) NOT NULL,
     CreatedAt DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
     CreatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
     UpdatedAt DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
     UpdatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM'
);

CREATE TABLE StockTransaction(
	 StockTransactionId INT PRIMARY KEY auto_increment,
	 SKUID VARCHAR(255) NOT NULL,
		 FOREIGN KEY (SKUID) REFERENCES MasterBarang(SKUID),
     GudangCode VARCHAR(255) NOT NULL,
	    FOREIGN KEY(GudangCode) REFERENCES MasterGudang(GudangCode),
     StockBefore INT NOT NULL,
     StockAfter INT NOT NULL,
	 StockIn INT,
	 StockOut INT,
	 CreatedAt DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
     CreatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
     UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
     UpdatedBy VARCHAR (255) NOT NULL DEFAULT 'SYSTEM'
);
